
# SITE SETTINGS
title: dataishuman
description: A website on the human side of data
owner:
  name:  # or company name
  email:
  url: https://dataishuman.github.io
first_published: 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dataishuman.github.io"


# GREETING ON LANDING PAGE
greeting:
  title: What is this, and why
  text: We believe the world has many stories to tell, and data is its language.


# WHO ARE WE ON LANDING PAGE
#who:
#  title: Who are we


# CONTACT ON LANDING PAGE
closing-head: Talk to us
closing-para: We always love a good chat


# SOCIAL BUTTONS ON ALL PAGES
social:
  twitter: todo
  github: https://github.com/dataishuman
  #linkedin-square:
  facebook-official: todo
  #google-plus-square:
  email: /contact/                      # goes to contact page
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:


# STUFF TO COMPILE VIA EDITOR USING compose.rb
compose:
  editor: subl
  extension: md


# BACK AND NEXT LINKS: WHERE? (top, bottom, both, none)
navlinks: none


# PIECES IN PROGRESS? (writing at bottom of pieces list appears?)
works_in_progress: yes


# CUSTOM EXTENSIONS (if any), in includes/_my/custom.scss
custom_extensions: no


# BUILD SETTINGS
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post


# TO INITIALISE ARRAYS IN ASSIGNEMENTS
# (assign myarr = site.empty_array,
# easier to grok than assign myarr = '' | split',')
empty_array: []
